# -*- coding: utf-8 -*-
"""setumon1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15YEqqOqulchERb9wubceGWWb_hDdpVQZ
"""

import csv
import pprint
with open('/samplelog.csv') as f:
 reader = csv.reader(f)
 l = [row for row in reader]
 ip= {r[1] for r in l}
for n in ip:
 ip_list=[r for r in l if r[1] == n]
 i=0
 while i<len(ip_list):
   if ip_list[i][2] == '-' :
     print(ip_list[i])
     while  i<len(ip_list) and ip_list[i][2] == '-' :
      i+=1
     if i >= len(ip_list):
       break
     print(ip_list[i]) 
   i+=1