# -*- coding: utf-8 -*-
"""setumon4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y5avAyj1JfPOXN1iMbt0ktSG8MS9-buJ
"""

import csv
import pprint
from ipaddress import ip_network

N = int(input('N='))
with open('/samplelog.csv') as f:
 reader = csv.reader(f)
 l = [row for row in reader]
ip= {r[1] for r in l}
sub_list = []
for n in ip:
 ip_list=[r for r in l if r[1] == n]
 i = 0
 y = 0
 while i<len(ip_list):
   if ip_list[i][2] == '-' :
     x=i
     while  i<len(ip_list) and ip_list[i][2] == '-' :
      i+=1
     if i >= len(ip_list):
       break
     if N<=i-x:
      print("ERROR")
      print(ip_list[x]) 
      print(ip_list[i])
   i+=1
ip_list = list(ip)
ip_error = [0] * len(ip_list)
subnet_list=[ip_network(n,strict=False) for r in ip_list]
subnet_d = list(set(subnet_list))
subnet_error = [0] * len(subnet_d)
subnet_c = [subnet_list.count(subnet) for subnet in subnet_d]
for i in l:
  if i[2] == '-':
    ip_error[ip_list.index(i[1])] = 1
  else:
    ip_error[ip_list.index(i[1])] = 0
  timeout_count = [0] * len(subnet_d)
  for j in range(len(ip_list)):
    subnet = subnet_list[j]
    subnet_d_index = subnet_d.index(subnet)
    timeout_count[subnet_d_index] += ip_error[j] 
  for j in range(len(subnet_d)):
    if subnet_error[j] == 0:
      if timeout_count[j] == subnet_c[j]:
        print(f"{i[0]},{subnet_d[j]} HINDRANCE")
        subnet_error[j] = 1
    else:
      if timeout_count[j] < subnet_c[j]:
        print(f"{i[0]},{subnet_d[j]} RETURN")
        subnet_error[j] = 0