# -*- coding: utf-8 -*-
"""setumon3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qql00MAINDYtJMk3N9s956v-qdic5Z6W
"""

import csv
import pprint
N = int(input('N='))
m = int(input('m='))
t = int(input('t='))
with open('/samplelog.csv') as f:
 reader = csv.reader(f)
 l = [row for row in reader]
 ip= {r[1] for r in l}
for n in ip:
 ip_list=[r for r in l if r[1] == n]
 i = 0
 y = 0
 while i<len(ip_list):
   if ip_list[i][2] == '-' :
     x=i
     while  i<len(ip_list) and ip_list[i][2] == '-' :
      i+=1
     if i >= len(ip_list):
       break
     if N<=i-x:
      print("ERROR")
      print(ip_list[x]) 
      print(ip_list[i])
   else:
    y += int(ip_list[i][2])
    if i-m >= 0 and ip_list[i-m][2] != '-':
     y -= int(ip_list[i-m][2])
    z=i 
    while t <= y/m:
      i+=1
      if i >= len(ip_list) or ip_list[i][2] == '-':
       break
      y += int(ip_list[i][2])
      if i-m >= 0:
       y -= int(ip_list[i-m][2])
   if z != i:
       print("OVERLOAD")
       print(ip_list[z]) 
       print(ip_list[i-1])
   i+=1